### ISSUE TITLE
Javascript problems

### ISSUE THREAD

**Issue by ekansa** [sarahmrowe/Virtual_Valdivia#2]
Hi Sarah!

First off, excellent looking site! It is beautiful! I'm going to jump into the weeds now to help debug the javascript issues so the Open Context search API works.

First off, if you're using the Chrome Browser, check out the "More Tools" -> "Developer Tools" feature. It can help you debug javascript.

The first problem I noticed is that you're page is not loading the Javascript file that I wrote for doing simple keyword searches with Open Context's API. In [line 24 of your data.html](https://github.com/sarahmrowe/Virtual_Valdivia/blob/gh-pages/data.html#L24) file, you've got:

```
<script src="../js/opencontext-simple.js"></script>
```

The "../js/opencontext-simple.js" is a relative link. That means a browser will be looking for the file in your own GitHub repository at this location: http://sarahmrowe.github.io/js/opencontext-simple.js and that file does not exist. So you need to either add that javascript file to your repository, or you need to change the location of where a browser should download that javascript file. You can get it directly from my repository here: http://ekansa.github.io/javascript/opencontext-simple.js

I'd actually recommend forking my API javascript repository (https://github.com/ekansa/ekansa.github.io) so you can edit my javascript as you need (and maybe merge improvements that I may make independently). Once you fork my repository, you can point to the version of the  "opencontext-simple.js" in your own forked repository, and thereby have control over it.

Last thing, Bootstrap javascript requires that you load JQuery before loading Bootstrap. Also my "opencontext-simple.js" depends on JQuery. So add a line to your data.html that tells a browser to download JQuery. You can get JQuery from Open Context:

```
<script src="https://opencontext.org/static/jquery/jquery-1.11.1.min.js"></script>
<script src="https://opencontext.org/static/jquery/ui/jquery-ui.min.js"></script>

```

or you can keep a copy local on your own repository, or you can load it from a source like Google (which serves JQuery very quickly):

```
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
```

I hope this helps!

**Comment by sarahmrowe** [comment]
I actually do have the opencontext-simple.js file in my js folder (I downloaded your repository to work with all this stuff). I downloaded jquery-3.1.0.min.js and added that to my js folder as well. do I just add 
`<script src="../js/jquery-3.1.0.min.js"></script>`
to line 25?

**Comment by sarahmrowe** [comment]
When I do the developer tools, these are the errors that come up:
- GET http://sarahmrowe.github.io/js/opencontext-simple.js  data.html:24
- Uncaught Error: Bootstrap's JavaScript requires jQuery(anonymous function) @ bootstrap.js:8  bootstrap.js:8 
- GET http://sarahmrowe.github.io/js/opencontext-simple.js 404 (Not Found)  data.html:24 
- Uncaught ReferenceError: OpenContextSimpleAPI is not defined  data.html:34

I'm really at a loss because I added the script you suggested, and the opencontext-simple.js file is in my js folder. It should be able to find it.

**Comment by sarahmrowe** [comment]
And if I click the search button, this additional error appears
"data.html:143 Uncaught TypeError: Cannot read property 'search' of undefinedonchange @ data.html:143
data.html:147 Uncaught TypeError: Cannot read property 'search' of undefinedonclick @ data.html:147"

**Comment by ekansa** [comment]
Sorry, back from helping my daughter with something. The error comes from. line 24 of your data.html file, you've got:

```
<script src="../js/opencontext-simple.js"></script>
```

The "../js/opencontext-simple.js" is a relative link, and a browser resolves that to look for the "opencontext-simple.js" file at this location: http://sarahmrowe.github.io/js/opencontext-simple.js

That is the wrong location, and the browser needs to find your file here:
http://sarahmrowe.github.io/Virtual_Valdivia/js/opencontext-simple.js

So, change line 24 of data.html to be: 

```
<script src="/js/opencontext-simple.js"></script>
```

or, you can change it to be:

```
<script src="http://sarahmrowe.github.io/Virtual_Valdivia/js/opencontext-simple.js"></script>
```

Next, I'd move these lines:

```
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
```

up a bit, to line 21 or so, since they should be loaded before the Bootstrap.js and the opencontext-simple.js, just to be sure.

:)

I hope this helps!
-Eric

**Comment by ekansa** [comment]
Sorry, make that

js/opencontext-simple.js

not 
/js/opencontext-simple.js

**Comment by ekansa** [comment]
I see the API is working now. I need to update the index to reflect your latest data. Please give me a few minutes (you'll get 404 errors sometimes until I finish the update)

**Comment by sarahmrowe** [comment]
This is fantastic! I'm working on translating portions of the site now, and will have artifact images ready for you soon!

**Comment by ekansa** [comment]
OK! I'm updating the index on Open Context, so it will return current results (no 404 errors). I'll add your pictures etc. when you're ready.

**Comment by ekansa** [comment]
OK. I purged deleted records from an earlier draft of your data from our index. You should be all set now to show results without 404 errors.
