### ISSUE TITLE
Pagination with the Open Context API

### ISSUE THREAD

**Issue by ekansa** [sarahmrowe/Virtual_Valdivia#3]
The easiest way to deal with pagination is to use the URLs to page through results provided by the Open Context API.

Here's an API response to a search for "incised":

https://opencontext.org/subjects-search/.json?proj=90-virtual-valdivia&prop=oc-gen-cat-object&attributes=thumbnail&sort=item--asc&start=0&rows=20&response=metadata%2Curi-meta&q=incised

The JSON response has this part, which has links to page through the results:

```
    "next": "https://opencontext.org/subjects-search/?rows=20&sort=item--asc&proj=90-virtual-valdivia&prop=oc-gen-cat-object&attributes=thumbnail&q=incised&start=20&response=metadata%2Curi-meta",
    "next-json": "https://opencontext.org/subjects-search/.json?rows=20&sort=item--asc&proj=90-virtual-valdivia&prop=oc-gen-cat-object&attributes=thumbnail&q=incised&start=20&response=metadata%2Curi-meta",
    "last": "https://opencontext.org/subjects-search/?rows=20&sort=item--asc&proj=90-virtual-valdivia&prop=oc-gen-cat-object&attributes=thumbnail&q=incised&start=220&response=metadata%2Curi-meta",
    "last-json": "https://opencontext.org/subjects-search/.json?rows=20&sort=item--asc&proj=90-virtual-valdivia&prop=oc-gen-cat-object&attributes=thumbnail&q=incised&start=220&response=metadata%2Curi-meta",
```

The "next" and "next-json" links are for paging to the next page of results. The "last" and "last-json" links are for paging to he last page of results. There are two sets of these paging links (with and without "-json") as a convenience to people who don't want to mess with something called "content negotiation". With content negotiation a browser can do things like specifically request the JSON version of a Web resource and not the HTML. Open Context supports content negotiation for JSON, but some people aren't familiar with content negotiation so we offer a slightly different hyperlink (the links with the "-json") to make it easier to get JSON and not HTML results.

Anyway, paging through results will require modifying the "opencontext-simple.js" file somewhat. If you feel like doing that and getting into the weeds with Javascript. I can help, but it will take a little programming!

**Comment by portableant** [comment]
Perhaps pagination is something we could collectively work on next week?

**Comment by sarahmrowe** [comment]
I'm certainly up for extra hands and greater knowledge!
